// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum CafeCharacterState : int
{
  None = 0,
  Idle = 1,
  Walk = 2,
  Reaction = 3,
  Interaction = 4,
  Max = 5,
};


}
