// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum DailyRefillType : int
{
  None = 0,
  Default = 1,
  Login = 2,
};


}
