// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum DreamMakerEndingType : int
{
  None = 0,
  Normal = 1,
  Special = 2,
};


}
