// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum DreamMakerParameterType : int
{
  None = 0,
  Param01 = 1,
  Param02 = 2,
  Param03 = 3,
  Param04 = 4,
};


}
