// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum FriendSearchLevelOption : int
{
  Recommend = 0,
  All = 1,
  Level1To30 = 2,
  Level31To40 = 3,
  Level41To50 = 4,
  Level51To60 = 5,
  Level61To70 = 6,
  Level71To80 = 7,
  Level81To90 = 8,
  Level91To100 = 9,
};


}
