// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::SCHALE.Common.Crypto;
using global::Google.FlatBuffers;

public struct GachaCraftNodeExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static GachaCraftNodeExcel GetRootAsGachaCraftNodeExcel(ByteBuffer _bb) { return GetRootAsGachaCraftNodeExcel(_bb, new GachaCraftNodeExcel()); }
  public static GachaCraftNodeExcel GetRootAsGachaCraftNodeExcel(ByteBuffer _bb, GachaCraftNodeExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GachaCraftNodeExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long Tier { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int QuickCraftNodeDisplayOrder { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long NodeQuality { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string Icon { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(12); }
  public uint LocalizeKey { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public long Property { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<SCHALE.Common.FlatData.GachaCraftNodeExcel> CreateGachaCraftNodeExcel(FlatBufferBuilder builder,
      long ID = 0,
      long Tier = 0,
      int QuickCraftNodeDisplayOrder = 0,
      long NodeQuality = 0,
      StringOffset IconOffset = default(StringOffset),
      uint LocalizeKey = 0,
      long Property = 0) {
    builder.StartTable(7);
    GachaCraftNodeExcel.AddProperty(builder, Property);
    GachaCraftNodeExcel.AddNodeQuality(builder, NodeQuality);
    GachaCraftNodeExcel.AddTier(builder, Tier);
    GachaCraftNodeExcel.AddID(builder, ID);
    GachaCraftNodeExcel.AddLocalizeKey(builder, LocalizeKey);
    GachaCraftNodeExcel.AddIcon(builder, IconOffset);
    GachaCraftNodeExcel.AddQuickCraftNodeDisplayOrder(builder, QuickCraftNodeDisplayOrder);
    return GachaCraftNodeExcel.EndGachaCraftNodeExcel(builder);
  }

  public static void StartGachaCraftNodeExcel(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddID(FlatBufferBuilder builder, long iD) { builder.AddLong(0, iD, 0); }
  public static void AddTier(FlatBufferBuilder builder, long tier) { builder.AddLong(1, tier, 0); }
  public static void AddQuickCraftNodeDisplayOrder(FlatBufferBuilder builder, int quickCraftNodeDisplayOrder) { builder.AddInt(2, quickCraftNodeDisplayOrder, 0); }
  public static void AddNodeQuality(FlatBufferBuilder builder, long nodeQuality) { builder.AddLong(3, nodeQuality, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset iconOffset) { builder.AddOffset(4, iconOffset.Value, 0); }
  public static void AddLocalizeKey(FlatBufferBuilder builder, uint localizeKey) { builder.AddUint(5, localizeKey, 0); }
  public static void AddProperty(FlatBufferBuilder builder, long property) { builder.AddLong(6, property, 0); }
  public static Offset<SCHALE.Common.FlatData.GachaCraftNodeExcel> EndGachaCraftNodeExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SCHALE.Common.FlatData.GachaCraftNodeExcel>(o);
  }
  public GachaCraftNodeExcelT UnPack() {
    var _o = new GachaCraftNodeExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(GachaCraftNodeExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("GachaCraftNode");
    _o.ID = TableEncryptionService.Convert(this.ID, key);
    _o.Tier = TableEncryptionService.Convert(this.Tier, key);
    _o.QuickCraftNodeDisplayOrder = TableEncryptionService.Convert(this.QuickCraftNodeDisplayOrder, key);
    _o.NodeQuality = TableEncryptionService.Convert(this.NodeQuality, key);
    _o.Icon = TableEncryptionService.Convert(this.Icon, key);
    _o.LocalizeKey = TableEncryptionService.Convert(this.LocalizeKey, key);
    _o.Property = TableEncryptionService.Convert(this.Property, key);
  }
  public static Offset<SCHALE.Common.FlatData.GachaCraftNodeExcel> Pack(FlatBufferBuilder builder, GachaCraftNodeExcelT _o) {
    if (_o == null) return default(Offset<SCHALE.Common.FlatData.GachaCraftNodeExcel>);
    var _Icon = _o.Icon == null ? default(StringOffset) : builder.CreateString(_o.Icon);
    return CreateGachaCraftNodeExcel(
      builder,
      _o.ID,
      _o.Tier,
      _o.QuickCraftNodeDisplayOrder,
      _o.NodeQuality,
      _Icon,
      _o.LocalizeKey,
      _o.Property);
  }
}

public class GachaCraftNodeExcelT
{
  public long ID { get; set; }
  public long Tier { get; set; }
  public int QuickCraftNodeDisplayOrder { get; set; }
  public long NodeQuality { get; set; }
  public string Icon { get; set; }
  public uint LocalizeKey { get; set; }
  public long Property { get; set; }

  public GachaCraftNodeExcelT() {
    this.ID = 0;
    this.Tier = 0;
    this.QuickCraftNodeDisplayOrder = 0;
    this.NodeQuality = 0;
    this.Icon = null;
    this.LocalizeKey = 0;
    this.Property = 0;
  }
}


static public class GachaCraftNodeExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ID*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Tier*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*QuickCraftNodeDisplayOrder*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*NodeQuality*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 12 /*Icon*/, false)
      && verifier.VerifyField(tablePos, 14 /*LocalizeKey*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*Property*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
