// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum GachaRewardType : int
{
  None = 0,
  Eligma = 1,
  Eleph = 2,
};


}
