// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::SCHALE.Common.Crypto;
using global::Google.FlatBuffers;

public struct LocalizeCharProfileExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static LocalizeCharProfileExcel GetRootAsLocalizeCharProfileExcel(ByteBuffer _bb) { return GetRootAsLocalizeCharProfileExcel(_bb, new LocalizeCharProfileExcel()); }
  public static LocalizeCharProfileExcel GetRootAsLocalizeCharProfileExcel(ByteBuffer _bb, LocalizeCharProfileExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LocalizeCharProfileExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long CharacterId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string StatusMessageKr { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStatusMessageKrBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetStatusMessageKrBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetStatusMessageKrArray() { return __p.__vector_as_array<byte>(6); }
  public string StatusMessageJp { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStatusMessageJpBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetStatusMessageJpBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetStatusMessageJpArray() { return __p.__vector_as_array<byte>(8); }
  public string FullNameKr { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFullNameKrBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetFullNameKrBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetFullNameKrArray() { return __p.__vector_as_array<byte>(10); }
  public string FullNameJp { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFullNameJpBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetFullNameJpBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetFullNameJpArray() { return __p.__vector_as_array<byte>(12); }
  public string FamilyNameKr { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFamilyNameKrBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetFamilyNameKrBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetFamilyNameKrArray() { return __p.__vector_as_array<byte>(14); }
  public string FamilyNameRubyKr { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFamilyNameRubyKrBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetFamilyNameRubyKrBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetFamilyNameRubyKrArray() { return __p.__vector_as_array<byte>(16); }
  public string PersonalNameKr { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPersonalNameKrBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetPersonalNameKrBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetPersonalNameKrArray() { return __p.__vector_as_array<byte>(18); }
  public string PersonalNameRubyKr { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPersonalNameRubyKrBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetPersonalNameRubyKrBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetPersonalNameRubyKrArray() { return __p.__vector_as_array<byte>(20); }
  public string FamilyNameJp { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFamilyNameJpBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetFamilyNameJpBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetFamilyNameJpArray() { return __p.__vector_as_array<byte>(22); }
  public string FamilyNameRubyJp { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFamilyNameRubyJpBytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetFamilyNameRubyJpBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetFamilyNameRubyJpArray() { return __p.__vector_as_array<byte>(24); }
  public string PersonalNameJp { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPersonalNameJpBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetPersonalNameJpBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetPersonalNameJpArray() { return __p.__vector_as_array<byte>(26); }
  public string PersonalNameRubyJp { get { int o = __p.__offset(28); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPersonalNameRubyJpBytes() { return __p.__vector_as_span<byte>(28, 1); }
#else
  public ArraySegment<byte>? GetPersonalNameRubyJpBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public byte[] GetPersonalNameRubyJpArray() { return __p.__vector_as_array<byte>(28); }
  public string SchoolYearKr { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSchoolYearKrBytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetSchoolYearKrBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetSchoolYearKrArray() { return __p.__vector_as_array<byte>(30); }
  public string SchoolYearJp { get { int o = __p.__offset(32); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSchoolYearJpBytes() { return __p.__vector_as_span<byte>(32, 1); }
#else
  public ArraySegment<byte>? GetSchoolYearJpBytes() { return __p.__vector_as_arraysegment(32); }
#endif
  public byte[] GetSchoolYearJpArray() { return __p.__vector_as_array<byte>(32); }
  public string CharacterAgeKr { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterAgeKrBytes() { return __p.__vector_as_span<byte>(34, 1); }
#else
  public ArraySegment<byte>? GetCharacterAgeKrBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public byte[] GetCharacterAgeKrArray() { return __p.__vector_as_array<byte>(34); }
  public string CharacterAgeJp { get { int o = __p.__offset(36); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterAgeJpBytes() { return __p.__vector_as_span<byte>(36, 1); }
#else
  public ArraySegment<byte>? GetCharacterAgeJpBytes() { return __p.__vector_as_arraysegment(36); }
#endif
  public byte[] GetCharacterAgeJpArray() { return __p.__vector_as_array<byte>(36); }
  public string BirthDay { get { int o = __p.__offset(38); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBirthDayBytes() { return __p.__vector_as_span<byte>(38, 1); }
#else
  public ArraySegment<byte>? GetBirthDayBytes() { return __p.__vector_as_arraysegment(38); }
#endif
  public byte[] GetBirthDayArray() { return __p.__vector_as_array<byte>(38); }
  public string BirthdayKr { get { int o = __p.__offset(40); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBirthdayKrBytes() { return __p.__vector_as_span<byte>(40, 1); }
#else
  public ArraySegment<byte>? GetBirthdayKrBytes() { return __p.__vector_as_arraysegment(40); }
#endif
  public byte[] GetBirthdayKrArray() { return __p.__vector_as_array<byte>(40); }
  public string BirthdayJp { get { int o = __p.__offset(42); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBirthdayJpBytes() { return __p.__vector_as_span<byte>(42, 1); }
#else
  public ArraySegment<byte>? GetBirthdayJpBytes() { return __p.__vector_as_arraysegment(42); }
#endif
  public byte[] GetBirthdayJpArray() { return __p.__vector_as_array<byte>(42); }
  public string CharHeightKr { get { int o = __p.__offset(44); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharHeightKrBytes() { return __p.__vector_as_span<byte>(44, 1); }
#else
  public ArraySegment<byte>? GetCharHeightKrBytes() { return __p.__vector_as_arraysegment(44); }
#endif
  public byte[] GetCharHeightKrArray() { return __p.__vector_as_array<byte>(44); }
  public string CharHeightJp { get { int o = __p.__offset(46); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharHeightJpBytes() { return __p.__vector_as_span<byte>(46, 1); }
#else
  public ArraySegment<byte>? GetCharHeightJpBytes() { return __p.__vector_as_arraysegment(46); }
#endif
  public byte[] GetCharHeightJpArray() { return __p.__vector_as_array<byte>(46); }
  public string DesignerNameKr { get { int o = __p.__offset(48); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDesignerNameKrBytes() { return __p.__vector_as_span<byte>(48, 1); }
#else
  public ArraySegment<byte>? GetDesignerNameKrBytes() { return __p.__vector_as_arraysegment(48); }
#endif
  public byte[] GetDesignerNameKrArray() { return __p.__vector_as_array<byte>(48); }
  public string DesignerNameJp { get { int o = __p.__offset(50); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDesignerNameJpBytes() { return __p.__vector_as_span<byte>(50, 1); }
#else
  public ArraySegment<byte>? GetDesignerNameJpBytes() { return __p.__vector_as_arraysegment(50); }
#endif
  public byte[] GetDesignerNameJpArray() { return __p.__vector_as_array<byte>(50); }
  public string IllustratorNameKr { get { int o = __p.__offset(52); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIllustratorNameKrBytes() { return __p.__vector_as_span<byte>(52, 1); }
#else
  public ArraySegment<byte>? GetIllustratorNameKrBytes() { return __p.__vector_as_arraysegment(52); }
#endif
  public byte[] GetIllustratorNameKrArray() { return __p.__vector_as_array<byte>(52); }
  public string IllustratorNameJp { get { int o = __p.__offset(54); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIllustratorNameJpBytes() { return __p.__vector_as_span<byte>(54, 1); }
#else
  public ArraySegment<byte>? GetIllustratorNameJpBytes() { return __p.__vector_as_arraysegment(54); }
#endif
  public byte[] GetIllustratorNameJpArray() { return __p.__vector_as_array<byte>(54); }
  public string CharacterVoiceKr { get { int o = __p.__offset(56); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterVoiceKrBytes() { return __p.__vector_as_span<byte>(56, 1); }
#else
  public ArraySegment<byte>? GetCharacterVoiceKrBytes() { return __p.__vector_as_arraysegment(56); }
#endif
  public byte[] GetCharacterVoiceKrArray() { return __p.__vector_as_array<byte>(56); }
  public string CharacterVoiceJp { get { int o = __p.__offset(58); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterVoiceJpBytes() { return __p.__vector_as_span<byte>(58, 1); }
#else
  public ArraySegment<byte>? GetCharacterVoiceJpBytes() { return __p.__vector_as_arraysegment(58); }
#endif
  public byte[] GetCharacterVoiceJpArray() { return __p.__vector_as_array<byte>(58); }
  public string HobbyKr { get { int o = __p.__offset(60); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHobbyKrBytes() { return __p.__vector_as_span<byte>(60, 1); }
#else
  public ArraySegment<byte>? GetHobbyKrBytes() { return __p.__vector_as_arraysegment(60); }
#endif
  public byte[] GetHobbyKrArray() { return __p.__vector_as_array<byte>(60); }
  public string HobbyJp { get { int o = __p.__offset(62); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetHobbyJpBytes() { return __p.__vector_as_span<byte>(62, 1); }
#else
  public ArraySegment<byte>? GetHobbyJpBytes() { return __p.__vector_as_arraysegment(62); }
#endif
  public byte[] GetHobbyJpArray() { return __p.__vector_as_array<byte>(62); }
  public string WeaponNameKr { get { int o = __p.__offset(64); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWeaponNameKrBytes() { return __p.__vector_as_span<byte>(64, 1); }
#else
  public ArraySegment<byte>? GetWeaponNameKrBytes() { return __p.__vector_as_arraysegment(64); }
#endif
  public byte[] GetWeaponNameKrArray() { return __p.__vector_as_array<byte>(64); }
  public string WeaponDescKr { get { int o = __p.__offset(66); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWeaponDescKrBytes() { return __p.__vector_as_span<byte>(66, 1); }
#else
  public ArraySegment<byte>? GetWeaponDescKrBytes() { return __p.__vector_as_arraysegment(66); }
#endif
  public byte[] GetWeaponDescKrArray() { return __p.__vector_as_array<byte>(66); }
  public string WeaponNameJp { get { int o = __p.__offset(68); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWeaponNameJpBytes() { return __p.__vector_as_span<byte>(68, 1); }
#else
  public ArraySegment<byte>? GetWeaponNameJpBytes() { return __p.__vector_as_arraysegment(68); }
#endif
  public byte[] GetWeaponNameJpArray() { return __p.__vector_as_array<byte>(68); }
  public string WeaponDescJp { get { int o = __p.__offset(70); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWeaponDescJpBytes() { return __p.__vector_as_span<byte>(70, 1); }
#else
  public ArraySegment<byte>? GetWeaponDescJpBytes() { return __p.__vector_as_arraysegment(70); }
#endif
  public byte[] GetWeaponDescJpArray() { return __p.__vector_as_array<byte>(70); }
  public string ProfileIntroductionKr { get { int o = __p.__offset(72); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProfileIntroductionKrBytes() { return __p.__vector_as_span<byte>(72, 1); }
#else
  public ArraySegment<byte>? GetProfileIntroductionKrBytes() { return __p.__vector_as_arraysegment(72); }
#endif
  public byte[] GetProfileIntroductionKrArray() { return __p.__vector_as_array<byte>(72); }
  public string ProfileIntroductionJp { get { int o = __p.__offset(74); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetProfileIntroductionJpBytes() { return __p.__vector_as_span<byte>(74, 1); }
#else
  public ArraySegment<byte>? GetProfileIntroductionJpBytes() { return __p.__vector_as_arraysegment(74); }
#endif
  public byte[] GetProfileIntroductionJpArray() { return __p.__vector_as_array<byte>(74); }
  public string CharacterSSRNewKr { get { int o = __p.__offset(76); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterSSRNewKrBytes() { return __p.__vector_as_span<byte>(76, 1); }
#else
  public ArraySegment<byte>? GetCharacterSSRNewKrBytes() { return __p.__vector_as_arraysegment(76); }
#endif
  public byte[] GetCharacterSSRNewKrArray() { return __p.__vector_as_array<byte>(76); }
  public string CharacterSSRNewJp { get { int o = __p.__offset(78); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCharacterSSRNewJpBytes() { return __p.__vector_as_span<byte>(78, 1); }
#else
  public ArraySegment<byte>? GetCharacterSSRNewJpBytes() { return __p.__vector_as_arraysegment(78); }
#endif
  public byte[] GetCharacterSSRNewJpArray() { return __p.__vector_as_array<byte>(78); }

  public static Offset<SCHALE.Common.FlatData.LocalizeCharProfileExcel> CreateLocalizeCharProfileExcel(FlatBufferBuilder builder,
      long CharacterId = 0,
      StringOffset StatusMessageKrOffset = default(StringOffset),
      StringOffset StatusMessageJpOffset = default(StringOffset),
      StringOffset FullNameKrOffset = default(StringOffset),
      StringOffset FullNameJpOffset = default(StringOffset),
      StringOffset FamilyNameKrOffset = default(StringOffset),
      StringOffset FamilyNameRubyKrOffset = default(StringOffset),
      StringOffset PersonalNameKrOffset = default(StringOffset),
      StringOffset PersonalNameRubyKrOffset = default(StringOffset),
      StringOffset FamilyNameJpOffset = default(StringOffset),
      StringOffset FamilyNameRubyJpOffset = default(StringOffset),
      StringOffset PersonalNameJpOffset = default(StringOffset),
      StringOffset PersonalNameRubyJpOffset = default(StringOffset),
      StringOffset SchoolYearKrOffset = default(StringOffset),
      StringOffset SchoolYearJpOffset = default(StringOffset),
      StringOffset CharacterAgeKrOffset = default(StringOffset),
      StringOffset CharacterAgeJpOffset = default(StringOffset),
      StringOffset BirthDayOffset = default(StringOffset),
      StringOffset BirthdayKrOffset = default(StringOffset),
      StringOffset BirthdayJpOffset = default(StringOffset),
      StringOffset CharHeightKrOffset = default(StringOffset),
      StringOffset CharHeightJpOffset = default(StringOffset),
      StringOffset DesignerNameKrOffset = default(StringOffset),
      StringOffset DesignerNameJpOffset = default(StringOffset),
      StringOffset IllustratorNameKrOffset = default(StringOffset),
      StringOffset IllustratorNameJpOffset = default(StringOffset),
      StringOffset CharacterVoiceKrOffset = default(StringOffset),
      StringOffset CharacterVoiceJpOffset = default(StringOffset),
      StringOffset HobbyKrOffset = default(StringOffset),
      StringOffset HobbyJpOffset = default(StringOffset),
      StringOffset WeaponNameKrOffset = default(StringOffset),
      StringOffset WeaponDescKrOffset = default(StringOffset),
      StringOffset WeaponNameJpOffset = default(StringOffset),
      StringOffset WeaponDescJpOffset = default(StringOffset),
      StringOffset ProfileIntroductionKrOffset = default(StringOffset),
      StringOffset ProfileIntroductionJpOffset = default(StringOffset),
      StringOffset CharacterSSRNewKrOffset = default(StringOffset),
      StringOffset CharacterSSRNewJpOffset = default(StringOffset)) {
    builder.StartTable(38);
    LocalizeCharProfileExcel.AddCharacterId(builder, CharacterId);
    LocalizeCharProfileExcel.AddCharacterSSRNewJp(builder, CharacterSSRNewJpOffset);
    LocalizeCharProfileExcel.AddCharacterSSRNewKr(builder, CharacterSSRNewKrOffset);
    LocalizeCharProfileExcel.AddProfileIntroductionJp(builder, ProfileIntroductionJpOffset);
    LocalizeCharProfileExcel.AddProfileIntroductionKr(builder, ProfileIntroductionKrOffset);
    LocalizeCharProfileExcel.AddWeaponDescJp(builder, WeaponDescJpOffset);
    LocalizeCharProfileExcel.AddWeaponNameJp(builder, WeaponNameJpOffset);
    LocalizeCharProfileExcel.AddWeaponDescKr(builder, WeaponDescKrOffset);
    LocalizeCharProfileExcel.AddWeaponNameKr(builder, WeaponNameKrOffset);
    LocalizeCharProfileExcel.AddHobbyJp(builder, HobbyJpOffset);
    LocalizeCharProfileExcel.AddHobbyKr(builder, HobbyKrOffset);
    LocalizeCharProfileExcel.AddCharacterVoiceJp(builder, CharacterVoiceJpOffset);
    LocalizeCharProfileExcel.AddCharacterVoiceKr(builder, CharacterVoiceKrOffset);
    LocalizeCharProfileExcel.AddIllustratorNameJp(builder, IllustratorNameJpOffset);
    LocalizeCharProfileExcel.AddIllustratorNameKr(builder, IllustratorNameKrOffset);
    LocalizeCharProfileExcel.AddDesignerNameJp(builder, DesignerNameJpOffset);
    LocalizeCharProfileExcel.AddDesignerNameKr(builder, DesignerNameKrOffset);
    LocalizeCharProfileExcel.AddCharHeightJp(builder, CharHeightJpOffset);
    LocalizeCharProfileExcel.AddCharHeightKr(builder, CharHeightKrOffset);
    LocalizeCharProfileExcel.AddBirthdayJp(builder, BirthdayJpOffset);
    LocalizeCharProfileExcel.AddBirthdayKr(builder, BirthdayKrOffset);
    LocalizeCharProfileExcel.AddBirthDay(builder, BirthDayOffset);
    LocalizeCharProfileExcel.AddCharacterAgeJp(builder, CharacterAgeJpOffset);
    LocalizeCharProfileExcel.AddCharacterAgeKr(builder, CharacterAgeKrOffset);
    LocalizeCharProfileExcel.AddSchoolYearJp(builder, SchoolYearJpOffset);
    LocalizeCharProfileExcel.AddSchoolYearKr(builder, SchoolYearKrOffset);
    LocalizeCharProfileExcel.AddPersonalNameRubyJp(builder, PersonalNameRubyJpOffset);
    LocalizeCharProfileExcel.AddPersonalNameJp(builder, PersonalNameJpOffset);
    LocalizeCharProfileExcel.AddFamilyNameRubyJp(builder, FamilyNameRubyJpOffset);
    LocalizeCharProfileExcel.AddFamilyNameJp(builder, FamilyNameJpOffset);
    LocalizeCharProfileExcel.AddPersonalNameRubyKr(builder, PersonalNameRubyKrOffset);
    LocalizeCharProfileExcel.AddPersonalNameKr(builder, PersonalNameKrOffset);
    LocalizeCharProfileExcel.AddFamilyNameRubyKr(builder, FamilyNameRubyKrOffset);
    LocalizeCharProfileExcel.AddFamilyNameKr(builder, FamilyNameKrOffset);
    LocalizeCharProfileExcel.AddFullNameJp(builder, FullNameJpOffset);
    LocalizeCharProfileExcel.AddFullNameKr(builder, FullNameKrOffset);
    LocalizeCharProfileExcel.AddStatusMessageJp(builder, StatusMessageJpOffset);
    LocalizeCharProfileExcel.AddStatusMessageKr(builder, StatusMessageKrOffset);
    return LocalizeCharProfileExcel.EndLocalizeCharProfileExcel(builder);
  }

  public static void StartLocalizeCharProfileExcel(FlatBufferBuilder builder) { builder.StartTable(38); }
  public static void AddCharacterId(FlatBufferBuilder builder, long characterId) { builder.AddLong(0, characterId, 0); }
  public static void AddStatusMessageKr(FlatBufferBuilder builder, StringOffset statusMessageKrOffset) { builder.AddOffset(1, statusMessageKrOffset.Value, 0); }
  public static void AddStatusMessageJp(FlatBufferBuilder builder, StringOffset statusMessageJpOffset) { builder.AddOffset(2, statusMessageJpOffset.Value, 0); }
  public static void AddFullNameKr(FlatBufferBuilder builder, StringOffset fullNameKrOffset) { builder.AddOffset(3, fullNameKrOffset.Value, 0); }
  public static void AddFullNameJp(FlatBufferBuilder builder, StringOffset fullNameJpOffset) { builder.AddOffset(4, fullNameJpOffset.Value, 0); }
  public static void AddFamilyNameKr(FlatBufferBuilder builder, StringOffset familyNameKrOffset) { builder.AddOffset(5, familyNameKrOffset.Value, 0); }
  public static void AddFamilyNameRubyKr(FlatBufferBuilder builder, StringOffset familyNameRubyKrOffset) { builder.AddOffset(6, familyNameRubyKrOffset.Value, 0); }
  public static void AddPersonalNameKr(FlatBufferBuilder builder, StringOffset personalNameKrOffset) { builder.AddOffset(7, personalNameKrOffset.Value, 0); }
  public static void AddPersonalNameRubyKr(FlatBufferBuilder builder, StringOffset personalNameRubyKrOffset) { builder.AddOffset(8, personalNameRubyKrOffset.Value, 0); }
  public static void AddFamilyNameJp(FlatBufferBuilder builder, StringOffset familyNameJpOffset) { builder.AddOffset(9, familyNameJpOffset.Value, 0); }
  public static void AddFamilyNameRubyJp(FlatBufferBuilder builder, StringOffset familyNameRubyJpOffset) { builder.AddOffset(10, familyNameRubyJpOffset.Value, 0); }
  public static void AddPersonalNameJp(FlatBufferBuilder builder, StringOffset personalNameJpOffset) { builder.AddOffset(11, personalNameJpOffset.Value, 0); }
  public static void AddPersonalNameRubyJp(FlatBufferBuilder builder, StringOffset personalNameRubyJpOffset) { builder.AddOffset(12, personalNameRubyJpOffset.Value, 0); }
  public static void AddSchoolYearKr(FlatBufferBuilder builder, StringOffset schoolYearKrOffset) { builder.AddOffset(13, schoolYearKrOffset.Value, 0); }
  public static void AddSchoolYearJp(FlatBufferBuilder builder, StringOffset schoolYearJpOffset) { builder.AddOffset(14, schoolYearJpOffset.Value, 0); }
  public static void AddCharacterAgeKr(FlatBufferBuilder builder, StringOffset characterAgeKrOffset) { builder.AddOffset(15, characterAgeKrOffset.Value, 0); }
  public static void AddCharacterAgeJp(FlatBufferBuilder builder, StringOffset characterAgeJpOffset) { builder.AddOffset(16, characterAgeJpOffset.Value, 0); }
  public static void AddBirthDay(FlatBufferBuilder builder, StringOffset birthDayOffset) { builder.AddOffset(17, birthDayOffset.Value, 0); }
  public static void AddBirthdayKr(FlatBufferBuilder builder, StringOffset birthdayKrOffset) { builder.AddOffset(18, birthdayKrOffset.Value, 0); }
  public static void AddBirthdayJp(FlatBufferBuilder builder, StringOffset birthdayJpOffset) { builder.AddOffset(19, birthdayJpOffset.Value, 0); }
  public static void AddCharHeightKr(FlatBufferBuilder builder, StringOffset charHeightKrOffset) { builder.AddOffset(20, charHeightKrOffset.Value, 0); }
  public static void AddCharHeightJp(FlatBufferBuilder builder, StringOffset charHeightJpOffset) { builder.AddOffset(21, charHeightJpOffset.Value, 0); }
  public static void AddDesignerNameKr(FlatBufferBuilder builder, StringOffset designerNameKrOffset) { builder.AddOffset(22, designerNameKrOffset.Value, 0); }
  public static void AddDesignerNameJp(FlatBufferBuilder builder, StringOffset designerNameJpOffset) { builder.AddOffset(23, designerNameJpOffset.Value, 0); }
  public static void AddIllustratorNameKr(FlatBufferBuilder builder, StringOffset illustratorNameKrOffset) { builder.AddOffset(24, illustratorNameKrOffset.Value, 0); }
  public static void AddIllustratorNameJp(FlatBufferBuilder builder, StringOffset illustratorNameJpOffset) { builder.AddOffset(25, illustratorNameJpOffset.Value, 0); }
  public static void AddCharacterVoiceKr(FlatBufferBuilder builder, StringOffset characterVoiceKrOffset) { builder.AddOffset(26, characterVoiceKrOffset.Value, 0); }
  public static void AddCharacterVoiceJp(FlatBufferBuilder builder, StringOffset characterVoiceJpOffset) { builder.AddOffset(27, characterVoiceJpOffset.Value, 0); }
  public static void AddHobbyKr(FlatBufferBuilder builder, StringOffset hobbyKrOffset) { builder.AddOffset(28, hobbyKrOffset.Value, 0); }
  public static void AddHobbyJp(FlatBufferBuilder builder, StringOffset hobbyJpOffset) { builder.AddOffset(29, hobbyJpOffset.Value, 0); }
  public static void AddWeaponNameKr(FlatBufferBuilder builder, StringOffset weaponNameKrOffset) { builder.AddOffset(30, weaponNameKrOffset.Value, 0); }
  public static void AddWeaponDescKr(FlatBufferBuilder builder, StringOffset weaponDescKrOffset) { builder.AddOffset(31, weaponDescKrOffset.Value, 0); }
  public static void AddWeaponNameJp(FlatBufferBuilder builder, StringOffset weaponNameJpOffset) { builder.AddOffset(32, weaponNameJpOffset.Value, 0); }
  public static void AddWeaponDescJp(FlatBufferBuilder builder, StringOffset weaponDescJpOffset) { builder.AddOffset(33, weaponDescJpOffset.Value, 0); }
  public static void AddProfileIntroductionKr(FlatBufferBuilder builder, StringOffset profileIntroductionKrOffset) { builder.AddOffset(34, profileIntroductionKrOffset.Value, 0); }
  public static void AddProfileIntroductionJp(FlatBufferBuilder builder, StringOffset profileIntroductionJpOffset) { builder.AddOffset(35, profileIntroductionJpOffset.Value, 0); }
  public static void AddCharacterSSRNewKr(FlatBufferBuilder builder, StringOffset characterSSRNewKrOffset) { builder.AddOffset(36, characterSSRNewKrOffset.Value, 0); }
  public static void AddCharacterSSRNewJp(FlatBufferBuilder builder, StringOffset characterSSRNewJpOffset) { builder.AddOffset(37, characterSSRNewJpOffset.Value, 0); }
  public static Offset<SCHALE.Common.FlatData.LocalizeCharProfileExcel> EndLocalizeCharProfileExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SCHALE.Common.FlatData.LocalizeCharProfileExcel>(o);
  }
  public LocalizeCharProfileExcelT UnPack() {
    var _o = new LocalizeCharProfileExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LocalizeCharProfileExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("LocalizeCharProfile");
    _o.CharacterId = TableEncryptionService.Convert(this.CharacterId, key);
    _o.StatusMessageKr = TableEncryptionService.Convert(this.StatusMessageKr, key);
    _o.StatusMessageJp = TableEncryptionService.Convert(this.StatusMessageJp, key);
    _o.FullNameKr = TableEncryptionService.Convert(this.FullNameKr, key);
    _o.FullNameJp = TableEncryptionService.Convert(this.FullNameJp, key);
    _o.FamilyNameKr = TableEncryptionService.Convert(this.FamilyNameKr, key);
    _o.FamilyNameRubyKr = TableEncryptionService.Convert(this.FamilyNameRubyKr, key);
    _o.PersonalNameKr = TableEncryptionService.Convert(this.PersonalNameKr, key);
    _o.PersonalNameRubyKr = TableEncryptionService.Convert(this.PersonalNameRubyKr, key);
    _o.FamilyNameJp = TableEncryptionService.Convert(this.FamilyNameJp, key);
    _o.FamilyNameRubyJp = TableEncryptionService.Convert(this.FamilyNameRubyJp, key);
    _o.PersonalNameJp = TableEncryptionService.Convert(this.PersonalNameJp, key);
    _o.PersonalNameRubyJp = TableEncryptionService.Convert(this.PersonalNameRubyJp, key);
    _o.SchoolYearKr = TableEncryptionService.Convert(this.SchoolYearKr, key);
    _o.SchoolYearJp = TableEncryptionService.Convert(this.SchoolYearJp, key);
    _o.CharacterAgeKr = TableEncryptionService.Convert(this.CharacterAgeKr, key);
    _o.CharacterAgeJp = TableEncryptionService.Convert(this.CharacterAgeJp, key);
    _o.BirthDay = TableEncryptionService.Convert(this.BirthDay, key);
    _o.BirthdayKr = TableEncryptionService.Convert(this.BirthdayKr, key);
    _o.BirthdayJp = TableEncryptionService.Convert(this.BirthdayJp, key);
    _o.CharHeightKr = TableEncryptionService.Convert(this.CharHeightKr, key);
    _o.CharHeightJp = TableEncryptionService.Convert(this.CharHeightJp, key);
    _o.DesignerNameKr = TableEncryptionService.Convert(this.DesignerNameKr, key);
    _o.DesignerNameJp = TableEncryptionService.Convert(this.DesignerNameJp, key);
    _o.IllustratorNameKr = TableEncryptionService.Convert(this.IllustratorNameKr, key);
    _o.IllustratorNameJp = TableEncryptionService.Convert(this.IllustratorNameJp, key);
    _o.CharacterVoiceKr = TableEncryptionService.Convert(this.CharacterVoiceKr, key);
    _o.CharacterVoiceJp = TableEncryptionService.Convert(this.CharacterVoiceJp, key);
    _o.HobbyKr = TableEncryptionService.Convert(this.HobbyKr, key);
    _o.HobbyJp = TableEncryptionService.Convert(this.HobbyJp, key);
    _o.WeaponNameKr = TableEncryptionService.Convert(this.WeaponNameKr, key);
    _o.WeaponDescKr = TableEncryptionService.Convert(this.WeaponDescKr, key);
    _o.WeaponNameJp = TableEncryptionService.Convert(this.WeaponNameJp, key);
    _o.WeaponDescJp = TableEncryptionService.Convert(this.WeaponDescJp, key);
    _o.ProfileIntroductionKr = TableEncryptionService.Convert(this.ProfileIntroductionKr, key);
    _o.ProfileIntroductionJp = TableEncryptionService.Convert(this.ProfileIntroductionJp, key);
    _o.CharacterSSRNewKr = TableEncryptionService.Convert(this.CharacterSSRNewKr, key);
    _o.CharacterSSRNewJp = TableEncryptionService.Convert(this.CharacterSSRNewJp, key);
  }
  public static Offset<SCHALE.Common.FlatData.LocalizeCharProfileExcel> Pack(FlatBufferBuilder builder, LocalizeCharProfileExcelT _o) {
    if (_o == null) return default(Offset<SCHALE.Common.FlatData.LocalizeCharProfileExcel>);
    var _StatusMessageKr = _o.StatusMessageKr == null ? default(StringOffset) : builder.CreateString(_o.StatusMessageKr);
    var _StatusMessageJp = _o.StatusMessageJp == null ? default(StringOffset) : builder.CreateString(_o.StatusMessageJp);
    var _FullNameKr = _o.FullNameKr == null ? default(StringOffset) : builder.CreateString(_o.FullNameKr);
    var _FullNameJp = _o.FullNameJp == null ? default(StringOffset) : builder.CreateString(_o.FullNameJp);
    var _FamilyNameKr = _o.FamilyNameKr == null ? default(StringOffset) : builder.CreateString(_o.FamilyNameKr);
    var _FamilyNameRubyKr = _o.FamilyNameRubyKr == null ? default(StringOffset) : builder.CreateString(_o.FamilyNameRubyKr);
    var _PersonalNameKr = _o.PersonalNameKr == null ? default(StringOffset) : builder.CreateString(_o.PersonalNameKr);
    var _PersonalNameRubyKr = _o.PersonalNameRubyKr == null ? default(StringOffset) : builder.CreateString(_o.PersonalNameRubyKr);
    var _FamilyNameJp = _o.FamilyNameJp == null ? default(StringOffset) : builder.CreateString(_o.FamilyNameJp);
    var _FamilyNameRubyJp = _o.FamilyNameRubyJp == null ? default(StringOffset) : builder.CreateString(_o.FamilyNameRubyJp);
    var _PersonalNameJp = _o.PersonalNameJp == null ? default(StringOffset) : builder.CreateString(_o.PersonalNameJp);
    var _PersonalNameRubyJp = _o.PersonalNameRubyJp == null ? default(StringOffset) : builder.CreateString(_o.PersonalNameRubyJp);
    var _SchoolYearKr = _o.SchoolYearKr == null ? default(StringOffset) : builder.CreateString(_o.SchoolYearKr);
    var _SchoolYearJp = _o.SchoolYearJp == null ? default(StringOffset) : builder.CreateString(_o.SchoolYearJp);
    var _CharacterAgeKr = _o.CharacterAgeKr == null ? default(StringOffset) : builder.CreateString(_o.CharacterAgeKr);
    var _CharacterAgeJp = _o.CharacterAgeJp == null ? default(StringOffset) : builder.CreateString(_o.CharacterAgeJp);
    var _BirthDay = _o.BirthDay == null ? default(StringOffset) : builder.CreateString(_o.BirthDay);
    var _BirthdayKr = _o.BirthdayKr == null ? default(StringOffset) : builder.CreateString(_o.BirthdayKr);
    var _BirthdayJp = _o.BirthdayJp == null ? default(StringOffset) : builder.CreateString(_o.BirthdayJp);
    var _CharHeightKr = _o.CharHeightKr == null ? default(StringOffset) : builder.CreateString(_o.CharHeightKr);
    var _CharHeightJp = _o.CharHeightJp == null ? default(StringOffset) : builder.CreateString(_o.CharHeightJp);
    var _DesignerNameKr = _o.DesignerNameKr == null ? default(StringOffset) : builder.CreateString(_o.DesignerNameKr);
    var _DesignerNameJp = _o.DesignerNameJp == null ? default(StringOffset) : builder.CreateString(_o.DesignerNameJp);
    var _IllustratorNameKr = _o.IllustratorNameKr == null ? default(StringOffset) : builder.CreateString(_o.IllustratorNameKr);
    var _IllustratorNameJp = _o.IllustratorNameJp == null ? default(StringOffset) : builder.CreateString(_o.IllustratorNameJp);
    var _CharacterVoiceKr = _o.CharacterVoiceKr == null ? default(StringOffset) : builder.CreateString(_o.CharacterVoiceKr);
    var _CharacterVoiceJp = _o.CharacterVoiceJp == null ? default(StringOffset) : builder.CreateString(_o.CharacterVoiceJp);
    var _HobbyKr = _o.HobbyKr == null ? default(StringOffset) : builder.CreateString(_o.HobbyKr);
    var _HobbyJp = _o.HobbyJp == null ? default(StringOffset) : builder.CreateString(_o.HobbyJp);
    var _WeaponNameKr = _o.WeaponNameKr == null ? default(StringOffset) : builder.CreateString(_o.WeaponNameKr);
    var _WeaponDescKr = _o.WeaponDescKr == null ? default(StringOffset) : builder.CreateString(_o.WeaponDescKr);
    var _WeaponNameJp = _o.WeaponNameJp == null ? default(StringOffset) : builder.CreateString(_o.WeaponNameJp);
    var _WeaponDescJp = _o.WeaponDescJp == null ? default(StringOffset) : builder.CreateString(_o.WeaponDescJp);
    var _ProfileIntroductionKr = _o.ProfileIntroductionKr == null ? default(StringOffset) : builder.CreateString(_o.ProfileIntroductionKr);
    var _ProfileIntroductionJp = _o.ProfileIntroductionJp == null ? default(StringOffset) : builder.CreateString(_o.ProfileIntroductionJp);
    var _CharacterSSRNewKr = _o.CharacterSSRNewKr == null ? default(StringOffset) : builder.CreateString(_o.CharacterSSRNewKr);
    var _CharacterSSRNewJp = _o.CharacterSSRNewJp == null ? default(StringOffset) : builder.CreateString(_o.CharacterSSRNewJp);
    return CreateLocalizeCharProfileExcel(
      builder,
      _o.CharacterId,
      _StatusMessageKr,
      _StatusMessageJp,
      _FullNameKr,
      _FullNameJp,
      _FamilyNameKr,
      _FamilyNameRubyKr,
      _PersonalNameKr,
      _PersonalNameRubyKr,
      _FamilyNameJp,
      _FamilyNameRubyJp,
      _PersonalNameJp,
      _PersonalNameRubyJp,
      _SchoolYearKr,
      _SchoolYearJp,
      _CharacterAgeKr,
      _CharacterAgeJp,
      _BirthDay,
      _BirthdayKr,
      _BirthdayJp,
      _CharHeightKr,
      _CharHeightJp,
      _DesignerNameKr,
      _DesignerNameJp,
      _IllustratorNameKr,
      _IllustratorNameJp,
      _CharacterVoiceKr,
      _CharacterVoiceJp,
      _HobbyKr,
      _HobbyJp,
      _WeaponNameKr,
      _WeaponDescKr,
      _WeaponNameJp,
      _WeaponDescJp,
      _ProfileIntroductionKr,
      _ProfileIntroductionJp,
      _CharacterSSRNewKr,
      _CharacterSSRNewJp);
  }
}

public class LocalizeCharProfileExcelT
{
  public long CharacterId { get; set; }
  public string StatusMessageKr { get; set; }
  public string StatusMessageJp { get; set; }
  public string FullNameKr { get; set; }
  public string FullNameJp { get; set; }
  public string FamilyNameKr { get; set; }
  public string FamilyNameRubyKr { get; set; }
  public string PersonalNameKr { get; set; }
  public string PersonalNameRubyKr { get; set; }
  public string FamilyNameJp { get; set; }
  public string FamilyNameRubyJp { get; set; }
  public string PersonalNameJp { get; set; }
  public string PersonalNameRubyJp { get; set; }
  public string SchoolYearKr { get; set; }
  public string SchoolYearJp { get; set; }
  public string CharacterAgeKr { get; set; }
  public string CharacterAgeJp { get; set; }
  public string BirthDay { get; set; }
  public string BirthdayKr { get; set; }
  public string BirthdayJp { get; set; }
  public string CharHeightKr { get; set; }
  public string CharHeightJp { get; set; }
  public string DesignerNameKr { get; set; }
  public string DesignerNameJp { get; set; }
  public string IllustratorNameKr { get; set; }
  public string IllustratorNameJp { get; set; }
  public string CharacterVoiceKr { get; set; }
  public string CharacterVoiceJp { get; set; }
  public string HobbyKr { get; set; }
  public string HobbyJp { get; set; }
  public string WeaponNameKr { get; set; }
  public string WeaponDescKr { get; set; }
  public string WeaponNameJp { get; set; }
  public string WeaponDescJp { get; set; }
  public string ProfileIntroductionKr { get; set; }
  public string ProfileIntroductionJp { get; set; }
  public string CharacterSSRNewKr { get; set; }
  public string CharacterSSRNewJp { get; set; }

  public LocalizeCharProfileExcelT() {
    this.CharacterId = 0;
    this.StatusMessageKr = null;
    this.StatusMessageJp = null;
    this.FullNameKr = null;
    this.FullNameJp = null;
    this.FamilyNameKr = null;
    this.FamilyNameRubyKr = null;
    this.PersonalNameKr = null;
    this.PersonalNameRubyKr = null;
    this.FamilyNameJp = null;
    this.FamilyNameRubyJp = null;
    this.PersonalNameJp = null;
    this.PersonalNameRubyJp = null;
    this.SchoolYearKr = null;
    this.SchoolYearJp = null;
    this.CharacterAgeKr = null;
    this.CharacterAgeJp = null;
    this.BirthDay = null;
    this.BirthdayKr = null;
    this.BirthdayJp = null;
    this.CharHeightKr = null;
    this.CharHeightJp = null;
    this.DesignerNameKr = null;
    this.DesignerNameJp = null;
    this.IllustratorNameKr = null;
    this.IllustratorNameJp = null;
    this.CharacterVoiceKr = null;
    this.CharacterVoiceJp = null;
    this.HobbyKr = null;
    this.HobbyJp = null;
    this.WeaponNameKr = null;
    this.WeaponDescKr = null;
    this.WeaponNameJp = null;
    this.WeaponDescJp = null;
    this.ProfileIntroductionKr = null;
    this.ProfileIntroductionJp = null;
    this.CharacterSSRNewKr = null;
    this.CharacterSSRNewJp = null;
  }
}


static public class LocalizeCharProfileExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CharacterId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*StatusMessageKr*/, false)
      && verifier.VerifyString(tablePos, 8 /*StatusMessageJp*/, false)
      && verifier.VerifyString(tablePos, 10 /*FullNameKr*/, false)
      && verifier.VerifyString(tablePos, 12 /*FullNameJp*/, false)
      && verifier.VerifyString(tablePos, 14 /*FamilyNameKr*/, false)
      && verifier.VerifyString(tablePos, 16 /*FamilyNameRubyKr*/, false)
      && verifier.VerifyString(tablePos, 18 /*PersonalNameKr*/, false)
      && verifier.VerifyString(tablePos, 20 /*PersonalNameRubyKr*/, false)
      && verifier.VerifyString(tablePos, 22 /*FamilyNameJp*/, false)
      && verifier.VerifyString(tablePos, 24 /*FamilyNameRubyJp*/, false)
      && verifier.VerifyString(tablePos, 26 /*PersonalNameJp*/, false)
      && verifier.VerifyString(tablePos, 28 /*PersonalNameRubyJp*/, false)
      && verifier.VerifyString(tablePos, 30 /*SchoolYearKr*/, false)
      && verifier.VerifyString(tablePos, 32 /*SchoolYearJp*/, false)
      && verifier.VerifyString(tablePos, 34 /*CharacterAgeKr*/, false)
      && verifier.VerifyString(tablePos, 36 /*CharacterAgeJp*/, false)
      && verifier.VerifyString(tablePos, 38 /*BirthDay*/, false)
      && verifier.VerifyString(tablePos, 40 /*BirthdayKr*/, false)
      && verifier.VerifyString(tablePos, 42 /*BirthdayJp*/, false)
      && verifier.VerifyString(tablePos, 44 /*CharHeightKr*/, false)
      && verifier.VerifyString(tablePos, 46 /*CharHeightJp*/, false)
      && verifier.VerifyString(tablePos, 48 /*DesignerNameKr*/, false)
      && verifier.VerifyString(tablePos, 50 /*DesignerNameJp*/, false)
      && verifier.VerifyString(tablePos, 52 /*IllustratorNameKr*/, false)
      && verifier.VerifyString(tablePos, 54 /*IllustratorNameJp*/, false)
      && verifier.VerifyString(tablePos, 56 /*CharacterVoiceKr*/, false)
      && verifier.VerifyString(tablePos, 58 /*CharacterVoiceJp*/, false)
      && verifier.VerifyString(tablePos, 60 /*HobbyKr*/, false)
      && verifier.VerifyString(tablePos, 62 /*HobbyJp*/, false)
      && verifier.VerifyString(tablePos, 64 /*WeaponNameKr*/, false)
      && verifier.VerifyString(tablePos, 66 /*WeaponDescKr*/, false)
      && verifier.VerifyString(tablePos, 68 /*WeaponNameJp*/, false)
      && verifier.VerifyString(tablePos, 70 /*WeaponDescJp*/, false)
      && verifier.VerifyString(tablePos, 72 /*ProfileIntroductionKr*/, false)
      && verifier.VerifyString(tablePos, 74 /*ProfileIntroductionJp*/, false)
      && verifier.VerifyString(tablePos, 76 /*CharacterSSRNewKr*/, false)
      && verifier.VerifyString(tablePos, 78 /*CharacterSSRNewJp*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
