// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PropRootMotionFlat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static PropRootMotionFlat GetRootAsPropRootMotionFlat(ByteBuffer _bb) { return GetRootAsPropRootMotionFlat(_bb, new PropRootMotionFlat()); }
  public static PropRootMotionFlat GetRootAsPropRootMotionFlat(ByteBuffer _bb, PropRootMotionFlat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PropRootMotionFlat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SCHALE.Common.FlatData.PropMotion? RootMotions(int j) { int o = __p.__offset(4); return o != 0 ? (SCHALE.Common.FlatData.PropMotion?)(new SCHALE.Common.FlatData.PropMotion()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RootMotionsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SCHALE.Common.FlatData.PropRootMotionFlat> CreatePropRootMotionFlat(FlatBufferBuilder builder,
      VectorOffset RootMotionsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    PropRootMotionFlat.AddRootMotions(builder, RootMotionsOffset);
    return PropRootMotionFlat.EndPropRootMotionFlat(builder);
  }

  public static void StartPropRootMotionFlat(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddRootMotions(FlatBufferBuilder builder, VectorOffset rootMotionsOffset) { builder.AddOffset(0, rootMotionsOffset.Value, 0); }
  public static VectorOffset CreateRootMotionsVector(FlatBufferBuilder builder, Offset<SCHALE.Common.FlatData.PropMotion>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRootMotionsVectorBlock(FlatBufferBuilder builder, Offset<SCHALE.Common.FlatData.PropMotion>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRootMotionsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SCHALE.Common.FlatData.PropMotion>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRootMotionsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SCHALE.Common.FlatData.PropMotion>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRootMotionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SCHALE.Common.FlatData.PropRootMotionFlat> EndPropRootMotionFlat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SCHALE.Common.FlatData.PropRootMotionFlat>(o);
  }
}


static public class PropRootMotionFlatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*RootMotions*/, SCHALE.Common.FlatData.PropMotionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
