// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum PurchaseStatusCode : int
{
  None = 0,
  Start = 1,
  PublishSuccess = 2,
  End = 3,
  Error = 4,
  DuplicateOrder = 5,
  Refund = 6,
};


}
