// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum RewardTag : int
{
  Default = 0,
  FirstClear = 1,
  StrategyObject = 2,
  Event = 3,
  ThreeStar = 4,
  ProductMonthly = 5,
  Rare = 6,
  EventBonus = 7,
  TimeWeight = 8,
  ProductWeekly = 9,
  ProductBiweekly = 10,
  EventPermanentReward = 11,
  ConquestManageEvent = 12,
  ConquestManageDefault = 13,
  ConquestCalculateDefault = 14,
  ConquestCalculateLevel2 = 15,
  ConquestCalculateLevel3 = 16,
  ConquestFootholdUpgrade2 = 17,
  ConquestFootholdUpgrade3 = 18,
  ConquestErosionPenalty = 19,
  GemBonus = 20,
  GemPaid = 21,
};


}
