// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum ShopFreeRecruitType : int
{
  None = 0,
  Accumulation = 1,
  Reset = 2,
};


}
