// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum SortingTarget : int
{
  None = 0,
  Rarity = 1,
  Level = 2,
  StarGrade = 3,
  Tier = 4,
};


}
