// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::SCHALE.Common.Crypto;
using global::Google.FlatBuffers;

public struct SpecialLobbyIllustExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static SpecialLobbyIllustExcel GetRootAsSpecialLobbyIllustExcel(ByteBuffer _bb) { return GetRootAsSpecialLobbyIllustExcel(_bb, new SpecialLobbyIllustExcel()); }
  public static SpecialLobbyIllustExcel GetRootAsSpecialLobbyIllustExcel(ByteBuffer _bb, SpecialLobbyIllustExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SpecialLobbyIllustExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long UniqueId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string DevName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDevNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDevNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDevNameArray() { return __p.__vector_as_array<byte>(6); }
  public long CharacterCostumeUniqueId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string PrefabName { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPrefabNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetPrefabNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetPrefabNameArray() { return __p.__vector_as_array<byte>(10); }
  public string SlotTextureName { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetSlotTextureNameBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetSlotTextureNameBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetSlotTextureNameArray() { return __p.__vector_as_array<byte>(12); }
  public string RewardTextureName { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRewardTextureNameBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetRewardTextureNameBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetRewardTextureNameArray() { return __p.__vector_as_array<byte>(14); }

  public static Offset<SCHALE.Common.FlatData.SpecialLobbyIllustExcel> CreateSpecialLobbyIllustExcel(FlatBufferBuilder builder,
      long UniqueId = 0,
      StringOffset DevNameOffset = default(StringOffset),
      long CharacterCostumeUniqueId = 0,
      StringOffset PrefabNameOffset = default(StringOffset),
      StringOffset SlotTextureNameOffset = default(StringOffset),
      StringOffset RewardTextureNameOffset = default(StringOffset)) {
    builder.StartTable(6);
    SpecialLobbyIllustExcel.AddCharacterCostumeUniqueId(builder, CharacterCostumeUniqueId);
    SpecialLobbyIllustExcel.AddUniqueId(builder, UniqueId);
    SpecialLobbyIllustExcel.AddRewardTextureName(builder, RewardTextureNameOffset);
    SpecialLobbyIllustExcel.AddSlotTextureName(builder, SlotTextureNameOffset);
    SpecialLobbyIllustExcel.AddPrefabName(builder, PrefabNameOffset);
    SpecialLobbyIllustExcel.AddDevName(builder, DevNameOffset);
    return SpecialLobbyIllustExcel.EndSpecialLobbyIllustExcel(builder);
  }

  public static void StartSpecialLobbyIllustExcel(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddUniqueId(FlatBufferBuilder builder, long uniqueId) { builder.AddLong(0, uniqueId, 0); }
  public static void AddDevName(FlatBufferBuilder builder, StringOffset devNameOffset) { builder.AddOffset(1, devNameOffset.Value, 0); }
  public static void AddCharacterCostumeUniqueId(FlatBufferBuilder builder, long characterCostumeUniqueId) { builder.AddLong(2, characterCostumeUniqueId, 0); }
  public static void AddPrefabName(FlatBufferBuilder builder, StringOffset prefabNameOffset) { builder.AddOffset(3, prefabNameOffset.Value, 0); }
  public static void AddSlotTextureName(FlatBufferBuilder builder, StringOffset slotTextureNameOffset) { builder.AddOffset(4, slotTextureNameOffset.Value, 0); }
  public static void AddRewardTextureName(FlatBufferBuilder builder, StringOffset rewardTextureNameOffset) { builder.AddOffset(5, rewardTextureNameOffset.Value, 0); }
  public static Offset<SCHALE.Common.FlatData.SpecialLobbyIllustExcel> EndSpecialLobbyIllustExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SCHALE.Common.FlatData.SpecialLobbyIllustExcel>(o);
  }
  public SpecialLobbyIllustExcelT UnPack() {
    var _o = new SpecialLobbyIllustExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SpecialLobbyIllustExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("SpecialLobbyIllust");
    _o.UniqueId = TableEncryptionService.Convert(this.UniqueId, key);
    _o.DevName = TableEncryptionService.Convert(this.DevName, key);
    _o.CharacterCostumeUniqueId = TableEncryptionService.Convert(this.CharacterCostumeUniqueId, key);
    _o.PrefabName = TableEncryptionService.Convert(this.PrefabName, key);
    _o.SlotTextureName = TableEncryptionService.Convert(this.SlotTextureName, key);
    _o.RewardTextureName = TableEncryptionService.Convert(this.RewardTextureName, key);
  }
  public static Offset<SCHALE.Common.FlatData.SpecialLobbyIllustExcel> Pack(FlatBufferBuilder builder, SpecialLobbyIllustExcelT _o) {
    if (_o == null) return default(Offset<SCHALE.Common.FlatData.SpecialLobbyIllustExcel>);
    var _DevName = _o.DevName == null ? default(StringOffset) : builder.CreateString(_o.DevName);
    var _PrefabName = _o.PrefabName == null ? default(StringOffset) : builder.CreateString(_o.PrefabName);
    var _SlotTextureName = _o.SlotTextureName == null ? default(StringOffset) : builder.CreateString(_o.SlotTextureName);
    var _RewardTextureName = _o.RewardTextureName == null ? default(StringOffset) : builder.CreateString(_o.RewardTextureName);
    return CreateSpecialLobbyIllustExcel(
      builder,
      _o.UniqueId,
      _DevName,
      _o.CharacterCostumeUniqueId,
      _PrefabName,
      _SlotTextureName,
      _RewardTextureName);
  }
}

public class SpecialLobbyIllustExcelT
{
  public long UniqueId { get; set; }
  public string DevName { get; set; }
  public long CharacterCostumeUniqueId { get; set; }
  public string PrefabName { get; set; }
  public string SlotTextureName { get; set; }
  public string RewardTextureName { get; set; }

  public SpecialLobbyIllustExcelT() {
    this.UniqueId = 0;
    this.DevName = null;
    this.CharacterCostumeUniqueId = 0;
    this.PrefabName = null;
    this.SlotTextureName = null;
    this.RewardTextureName = null;
  }
}


static public class SpecialLobbyIllustExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*UniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*DevName*/, false)
      && verifier.VerifyField(tablePos, 8 /*CharacterCostumeUniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 10 /*PrefabName*/, false)
      && verifier.VerifyString(tablePos, 12 /*SlotTextureName*/, false)
      && verifier.VerifyString(tablePos, 14 /*RewardTextureName*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
