// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum TBGItemEffectType : int
{
  None = 0,
  PermanentContinuity = 1,
  TemporaryContinuation = 2,
  Immediately = 3,
};


}
