// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum VoiceEvent : int
{
  OnTSA = 0,
  FormationPickUp = 1,
  CampaignResultDefeat = 2,
  CampaignResultVictory = 3,
  CharacterLevelUp = 4,
  CharacterTranscendence = 5,
  SkillLevelUp = 6,
  Formation = 7,
  CampaignCharacterSpawn = 8,
  BattleStartTimeline = 9,
  BattleVictoryTimeline = 10,
  CharacterFavor = 11,
  BattleMiss = 12,
  BattleBlock = 13,
  BattleCover = 14,
  BattleMove = 15,
  BattleMoveToForamtionBeacon = 16,
  MGS_GameStart = 17,
  MGS_CharacterSelect = 18,
  MGS_Attacking = 19,
  MGS_GeasGet = 20,
  EXSkill = 21,
  EXSkillLevel = 22,
  EXSkill2 = 23,
  EXSkillLevel2 = 24,
  EXSkill3 = 25,
  EXSkillLevel3 = 26,
  EXSkill4 = 27,
  EXSkillLevel4 = 28,
  PublicSkill01 = 29,
  PublicSkill02 = 30,
  InteractionPublicSkill01 = 31,
  InteractionPublicSkill02 = 32,
};


}
