// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SCHALE.Common.FlatData
{

public enum WebAPIErrorLevel : int
{
  None = 0,
  Warning = 1,
  Error = 2,
};


}
